# Site settings
title: Bruno Milhan
header-img: img/home-bg.jpg
email: brunomilhan@gmail.com
description: "test theme!"
baseurl: ""
url: "http:/brunomilhan.github.io/"
twitter_username: brunomilhan
github_username:  brunomilhan
facebook_username:  brunomilhan

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
