# Site settings
title: "Bruno Milhan"
header-img: img/home-bg.jpg
email: brunomilhan@gmail.com
description: "Dev. mobile/web/backend"
baseurl: ""
url: "http:/brunomilhan.github.io/"
twitter_username: 
github_username:  brunomilhan
facebook_username:  brunomilhan
linkedin_username:  "https://br.linkedin.com/pub/bruno-milhan/51/214/28/pt"
# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
